### ISSUE TITLE
About sentinel-load event

### ISSUE THREAD

**Issue by TheMushrr00m** [muicss/sentineljs#10]
Hi, maybe this is a very newbie question but, 

In your dist version you have this code to dispatch the event
```
// dispatch load event
  ev = doc.createEvent('HTMLEvents');
  ev.initEvent('sentinel-load', false, false);
doc.dispatchEvent(ev);``
```
But where is it in the src version?

How did you get that? I'm trying to understand it but i can't  😢

**Comment by amorey** [comment]
It's in `umd-templates/web.js` which is used to create a package for the browser:
https://github.com/muicss/sentineljs/blob/master/umd-templates/web.js

**Comment by TheMushrr00m** [comment]
Thanks for reply, this is helpful to me. 

Continue with this great job.
