### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by rahilwazir** [muicss/sentineljs#6]
![sentinel](https://user-images.githubusercontent.com/1818941/30627700-5c675d58-9deb-11e7-97b0-aeaa4d10f5af.png)

**Comment by amorey** [comment]
Hmm... that's strange. I just checked in all major browsers (IE10+, Chrome, Firefox, etc.) and it worked for me. Based on the error message it looks like your browser wasn't able to load the external `sentinel.js` file hosted at cdn.rawgit.com. What is your browser/os? Are you having trouble accessing this file?
https://cdn.rawgit.com/muicss/sentineljs/0.0.1/dist/sentinel.min.js

Here's the demo url:
https://jsfiddle.net/muicss/rbqLbjzf/

**Comment by rahilwazir** [comment]
Strangely, its working now. I guess a temporary issue.

**Comment by amorey** [comment]
Great! Thanks for checking! Maybe there was an issue with the rawgit CDN.
